config/routes.rb
Leboncouac::Application.routes.draw do
  resources :instruments

  resources :musicians  do
    get :activation, on: :collection
    put :send_message, on: :member
  end

  get "home/index"

  root :to => 'musicians#index'

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_and_belongs_to_many :musicians
end

app/models/musician.rb
# encoding: utf-8
require 'securerandom'

class Musician < ActiveRecord::Base
  
    DEPARTMENTS = [
      "1 Ain",
      "2 Aisne",
      "3 Allier",
      "4 Alpes-de-Haute-Provence",
      "5 Haute-Alpes",
      "6 Alpes-Maritimes",
      "7 Ardèche",
      "8 Ardennes",
      "9 Ariège",
      "10 Aube",
      "11 Aude",
      "12 Aveyron",
      "13 Bouches-du-Rhône",
      "14 Calvados", 
      "15 Cantal", 
      "16 Charente", 
      "17 Charente-Maritime",
      "18 Cher", 
      "19 Corrèze", 
      "2A Corse-du-Sud",
      "2B Haute-Corse",
      "21 Côte-d'Or",
      "22 Côtes-d'Armor",
      "23 Creuse", 
      "24 Dordogne", 
      "25 Doubs", 
      "26 Drôme",
      "27 Eure",
      "28 Eure-et-Loir",
      "29 Finistère",
      "30 Gard",
      "31 Haute-Garonne",
      "32 Gers",
      "33 Gironde",
      "34 Hérault",
      "35 Ille-et-Vilaine",
      "36 Indre",
      "37 Indre-et-Loire",
      "38 Isère",
      "39 Jura",
      "40 Landes",
      "41 Loir-et-Cher",
      "42 Loire",
      "43 Haute-Loire",
      "44 Loire-Atlantique",
      "45 Loiret",
      "46 Lot",
      "47 Lot-et-Garonne",
      "48 Lozère",
      "49 Maine-et-Loire",
      "50 Manche",
      "51 Marne",
      "52 Haute-Marne",
      "53 Mayenne",
      "54 Meurthe-et-Moselle",
      "55 Meuse",
      "56 Morbihan",
      "57 Moselle",
      "58 Nièvre",
      "59 Nord",
      "60 Oise",
      "61 Orne",
      "62 Pas-de-Calais",
      "63 Puy-de-Dôme",
      "64 Pyrénées-Atlantiques",
      "65 Hautes-Pyrénées",
      "66 Pyrénées-Orientales",
      "67 Bas-Rhin",
      "68 Haut-Rhin",
      "69 Rhône",
      "70 Haute-Saône",
      "71 Saône-et-Loire",
      "72 Sarthe",
      "73 Savoie",
      "74 Haute-Savoie",
      "75 Paris",
      "76 Seine-Maritime",
      "77 Seine-et-Marne",
      "78 Yvelines",
      "79 Deux-Sèvres",
      "80 Somme",
      "81 Tarn",
      "82 Tarn-et-Garonne",
      "83 Var",
      "84 Vaucluse",
      "85 Vendée",
      "86 Vienne",
      "87 Haute-Vienne",
      "88 Vosges",
      "89 Yonne",
      "90 Territoire de Belfort",
      "91 Essonne",
      "92 Hauts-de-Seine",
      "93 Seine-Saint-Denis",
      "94 Val-de-Marne",
      "95 Val-d'Oise",
      "971 Guadeloupe",
      "972 Martinique",
      "973 Guyanne",
      "974 La Réunion",
      "976 Mayotte"]
      
    LEVELS = [
      "Débutant",
       "Moyen",
       "Confirmé",
       "Professionnel"]
    
    #validates_presence_of :name, :email
    before_create :generate_uuid
    has_and_belongs_to_many :instruments
    
    def generate_uuid()
      self.uuid = SecureRandom.urlsafe_base64()
    end
    
    def is_active
      active
    end
    
    def set_active
      self.active = true
    end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instruments }
    end
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
    @instrument = Instrument.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instrument }
    end
  end

  # GET /instruments/new
  # GET /instruments/new.json
  def new
    @instrument = Instrument.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instrument }
    end
  end

  # GET /instruments/1/edit
  def edit
    @instrument = Instrument.find(params[:id])
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(params[:instrument])

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render json: @instrument, status: :created, location: @instrument }
      else
        format.html { render action: "new" }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instruments/1
  # PUT /instruments/1.json
  def update
    @instrument = Instrument.find(params[:id])

    respond_to do |format|
      if @instrument.update_attributes(params[:instrument])
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy

    respond_to do |format|
      format.html { redirect_to instruments_url }
      format.json { head :ok }
    end
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  # GET /musicians
  # GET /musicians.json
  def index
    @musicians = Musician.all.find_all { |musician| musician.is_active }
     @musician = Musician.new
      @instruments = Instrument.find(:all, :order => "name")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musicians }
    end
  end

  # GET /musicians/1
  # GET /musicians/1.json
  def show
    @musician = Musician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @musician }
    end
  end

  # GET /musicians/new
  # GET /musicians/new.json
  def new
    @musician = Musician.new
    @instruments = Instrument.find(:all, :order => "name")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @musician }
    end
  end

  # GET /musicians/1/edit
  def edit
    @musician = Musician.find(params[:id])
    @instruments = Instrument.find(:all, :order => "name")
  end

  # POST /musicians
  # POST /musicians.json
  def create
    @musician = Musician.new(params[:musician])
    @instruments = Instrument.find(:all, :order => "name")
    
    respond_to do |format|
      if @musician.save
        UserMailer.subscribeDemand(@musician).deliver
        format.js
        format.html { redirect_to @musician, notice: t(:Inscription_complete) }
        format.json { render json: @musician, status: :created, location: @musician }
        @musician = Musician.new
      else
        format.js { render js: @musician.errors, :status => :unprocessable_entity }
        format.html { render action: "new" }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musicians/1
  # PUT /musicians/1.json
  def update
    @musician = Musician.find(params[:id])

    respond_to do |format|
      if @musician.update_attributes(params[:musician])
        format.html { redirect_to @musician, notice: 'Musician was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicians/1
  # DELETE /musicians/1.json
  def destroy
    @musician = Musician.find(params[:id])
    @musician.destroy

    respond_to do |format|
      format.html { redirect_to musicians_url }
      format.json { head :ok }
    end
  end
  
  # GET /musicians/?:uuid
  def activation
    @musician = Musician.all.find { |musician| musician.uuid == params[:uuid] }
    @musician.set_active

    respond_to do |format|
       if @musician.save
         format.html { redirect_to musicians_url }
         format.json { head :ok }
       else
         format.html { render action: "activation" }
         format.json { render json: @musician.errors, status: :unprocessable_entity }
       end
    end
  end
  
  def send_message
    @musician = Musician.find(params[:id])
    name = params[:name]
    email = params[:email]
    phone = params[:phone]
    message = params[:message]
    UserMailer.sendMessage(@musician, name, email, phone, message).deliver
    
    respond_to do |format|
         format.html { redirect_to musicians_url }
         format.json { head :ok }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leboncouac</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png"  href="<%= image_path 'favicon.png' %>"/>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/musicians/_form.html.erb
<p>
Vous désirez être contacté par des groupes de musique à la recherche de musiciens et de chanteurs ?
<br>Inscrivez-vous gratuitement via ce formulaire.
<br>Votre annonce restera pendant 3 mois sur le site puis sera supprimée. Pendant cette période, vous pourrez la supprimer à tout moment.
<br><br>
</p>

<%= form_for(@musician, :remote => true, :id => "musician_form") do |f| %>

<div class="errors"></div>
  

  <div class="field">
    <label>Nom</label>
    <%= f.text_field :name, {:class => 'text ui-widget-content ui-corner-all'} %>
  </div>

 <div class="field">
	Instruments<br />
  	<%= collection_select(:musician, :instrument_ids, @instruments, :id, :name, {:prompt => false}, { :multiple => true, :class => 'ui-widget-content ui-corner-all'}) %>
  </div>

  <div class="field">
	Niveau<br />
  	<%= select(:musician, :level, Musician::LEVELS, {:prompt => "Sélectionner votre niveau"}, {:class => 'ui-widget-content ui-corner-all'}) %>
  </div>

  <div class="field">
    Styles joués<br />
    <%= f.text_field :style, {:class => 'text ui-widget-content ui-corner-all'} %>
  </div>

 <div class="field">
	Département<br />
  	<%= select(:musician, :department, Musician::DEPARTMENTS, {:prompt => "Sélectionner un département"}, {:class => 'ui-widget-content ui-corner-all'}) %>
  </div>
  
  <div class="field">
    Ville<br />
    <%= f.text_field :city, {:class => 'text ui-widget-content ui-corner-all'} %>
  </div>

 <div class="field">
    Ajouter des informations supplémentaires<br />
    <div class="form_texarea_wrapper"><%= f.text_area :comment, {:class => 'text ui-widget-content ui-corner-all form_textarea', :rows => 10, :cols => 70} %></div>
  </div>

  <div class="field">
    Email<br />
    <%= f.text_field :email, {:class => 'text ui-widget-content ui-corner-all'} %>
	<br />Afin de vous protéger du spam, votre email ne sera pas visible dans l'annonce. Les utilisateurs pourront vous contacter via un formulaire.
  </div>

  <div class="actions">
    <%= f.submit "S'inscrire", {:class => 'inscription_button'} %>
  </div>
<% end %>

<div id="dialog-confirm" title="Inscription complète!">
	<p>
		<span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
		Votre demande d'inscription est prise en compte. Vous allez recevoir un email pour la valider.
	</p>
</div>

app/views/musicians/create.js.erb
var el = $('#musician_form');

<% if @musician.errors.any? %>

  // Create a list of errors
  var errors = $('<ul />');

  <% @musician.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>

  // Display errors on form
  el.find('.errors').html(errors);

<% else %>


$('#musician_name').val('');
$('#musician_instrument_ids').val('');
$('#musician_level').val('');
$('#musician_style').val('');
$('#musician_department').val('');
$('#musician_city').val('');
$('#musician_comment').val('');
$('#musician_email').val('');
	
$("#dialog-confirm").dialog({
	autoOpen: false,
	modal: true,
	buttons: {
		Ok: function() {
			$( this ).dialog("close");
			$("#dialog-confirm").hide();
			$("#tab_all_musicians").trigger('click');
			$("body").scrollTop(0);
		}
	}
});


$("#dialog-confirm").show();
$("#dialog-confirm").dialog("open");						
 

<% end %>

app/views/musicians/index.html.erb
<div id="bandeau"></div>

<div id="main">
    <div id="entete"><img src="<%= image_path 'leboncouac-beige-200.png' %>"/></div>

    <div id="onglets">
        <a role="button" class="button onglet_1" href="#accueil">Accueil</a>
        <a role="button" class="button" href="#all-musicians" id="tab_all_musicians">Recherche</a>
        <a role="button" class="button" href="#new-musician">Inscription</a>
        <div class="onglet" id="accueil">
            <h3>Accueil</h3>
            <p>Avec leboncouac.fr, formez votre groupe de musique facilement !</p>
            <br/>

            <h4>Vous êtes musicien et vous cherchez un groupe ?</h4>
            <p>Inscrivez-vous via le formulaire d'inscription !
            <br>Vous pourrez alors être contactés par les groupes de musique de votre région à la recherche d'un musicien correspondant à votre profil.
            </p>
            <br/>

            <h4>Vous faites partie d'un groupe et il vous manque un musicien ?</h4>
            <p>Contactez les musiciens dont vous avez besoin !
            <br>L'onglet de recherche permet de trier les musiciens en fonction des critères de votre choix.
                Une fois le musicien correspondant trouvé, il ne vous reste plus qu'à le contacter via le formulaire de contact.
            </p>
            <br/>

            <h4>Vous avez une remarque, une question ?</h4>
            <p>N'hésitez pas à nous contacter !
            <br>Contact : <%= mail_to "contact@leboncouac.fr" %>
            </p>
        </div>
        <div class="onglet" id="all-musicians">
        	<h3>Liste des musiciens</h3>

			<p>Liste des musiciens cherchant à jouer dans un groupe.
			<br>Faites une recherche dans la liste ci dessous (n'oubliez pas de la trier en fonction des critères qui sont importants pour vous), puis contactez les via le formulaire (bouton 'Contact').
			<br><br>
			</p>

			<table id="musician_table" class="tablesorter">
			  <thead> 
			  <tr>
			    <th class="bordered">Nom</th>
			    <th class="bordered">Instruments</th>
			    <th class="bordered">Niveau</th>
			    <th class="bordered">Styles</th>
			    <th class="bordered">Département</th>
			    <th class="bordered">Ville</th>
				<th></th>
				<th></th>
			  </tr>
			  </thead> 

			  <tbody>
			<% @musicians.each do |musician| %>
			  <tr>
			    <td class="bordered"><%= musician.name %></td>
			 	<td class="bordered"><%= musician.instruments.map { |instrument| instrument.name }.join(", ") %></td>
			    <td class="bordered"><%= musician.level %></td>
			    <td class="bordered"><%= musician.style %></td>
			    <td class="bordered"><%= musician.department %></td>
			    <td class="bordered"><%= musician.city %></td>
			
				<td><button class="detail_musician" musician_detail_name="<%=h musician.name %>" musician_detail_detail="<%=h musician.comment %>">+</button></td>
				<td><button class="contact_musician" musician_contact_name="<%=h musician.name %>" musician_contact_url="<%= send_message_musician_url(musician) %>">Contact</button></td>
				
			  </tr>
			<% end %>
			  </tbody>
			</table>
        </div>

        <div class="onglet" id="new-musician">
			<%= render 'form' %>			
        </div>
    </div>

    <div id="publicite">
    </div>

</div>

<div id="dialog-contact">
  <form id="contact_form">
	<fieldset>
		<label id="contact"></label>
		<label for="name">Nom</label>
		<input type="text" name="name" id="name" class="text ui-widget-content ui-corner-all" />
		<label for="email">Email</label>
		<input type="text" name="email" id="email" value="" class="text ui-widget-content ui-corner-all" />
		<label for="phone">Téléphone</label>
		<input type="text" name="phone" id="phone" value="" class="text ui-widget-content ui-corner-all" />
		<label for="message">Message</label>
		<textarea rows=7  cols=70 name="message" id="message" value="" class="text ui-widget-content ui-corner-all"></textarea>		
	</fieldset>
  </form>
</div>

<div id="dialog-detail">
		<label id="dialog-detail-label">Informations complémentaires</label>
</div>

app/views/musicians/new.html.erb
<h3>Inscription</h3>

<%= render 'form' %>